name: telegram_mini_app
description: A simple Telegram Mini App built with Flutter
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.2.2
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  # Removed uses-material-design to avoid Roboto font loading errors
  # Using system fonts instead
  
  # Assets folder (for images used in Flutter code)
  assets:
    - assets/images/logo.svg
    - assets/icons/apply.svg
    - assets/icons/connect.svg
    - assets/icons/create.svg
    - assets/icons/import.svg
    - assets/sample/1.png
    - assets/sample/2.png
    - assets/sample/3.png
    - assets/sample/4.png
    - assets/sample/5.png
  
  # Fonts configuration
  fonts:
    - family: Aeroport
      fonts:
        - asset: assets/fonts/AEROPORT-REGULAR-TRIAL.OTF
          weight: 400
        - asset: assets/fonts/AEROPORT-LIGHT-TRIAL.OTF
          weight: 300
        - asset: assets/fonts/AEROPORT-MEDIUM-TRIAL.OTF
          weight: 500
        - asset: assets/fonts/AEROPORT-BOLD-TRIAL.OTF
          weight: 700
        - asset: assets/fonts/AEROPORT-BLACK.OTF
          weight: 900


